package pojos;
// Generated Oct 31, 2018 2:37:47 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Antrian generated by hbm2java
 */
@Entity
@Table(name="antrian"
    ,catalog="rsku"
)
public class Antrian  implements java.io.Serializable {


     private Long id;
     private Date tanggal;
     private String noRm;
     private String nama;
     private String alamat;
     private String namaKlinik;

    public Antrian() {
    }

    public Antrian(Date tanggal, String noRm, String nama, String alamat, String namaKlinik) {
       this.tanggal = tanggal;
       this.noRm = noRm;
       this.nama = nama;
       this.alamat = alamat;
       this.namaKlinik = namaKlinik;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="tanggal", length=10)
    public Date getTanggal() {
        return this.tanggal;
    }
    
    public void setTanggal(Date tanggal) {
        this.tanggal = tanggal;
    }

    
    @Column(name="noRm", length=20)
    public String getNoRm() {
        return this.noRm;
    }
    
    public void setNoRm(String noRm) {
        this.noRm = noRm;
    }

    
    @Column(name="nama", length=25)
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }

    
    @Column(name="alamat", length=65535)
    public String getAlamat() {
        return this.alamat;
    }
    
    public void setAlamat(String alamat) {
        this.alamat = alamat;
    }

    
    @Column(name="namaKlinik", length=50)
    public String getNamaKlinik() {
        return this.namaKlinik;
    }
    
    public void setNamaKlinik(String namaKlinik) {
        this.namaKlinik = namaKlinik;
    }




}


