package pojos;
// Generated Oct 31, 2018 2:37:47 PM by Hibernate Tools 4.3.1

import helper.LocationHelper;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Location generated by hbm2java
 */
@Entity
@Table(name = "location",
         catalog = "rsku"
)
public class Location implements java.io.Serializable {

    private Long id;
    private Double lat;
    private Double lng;
    private String name;

    public Location() {
    }

    public Location(Double lat, Double lng, String name) {
        this.lat = lat;
        this.lng = lng;
        this.name = name;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id", unique = true, nullable = false)
    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @Column(name = "lat", precision = 22, scale = 0)
    public Double getLat() {
        return this.lat;
    }

    public void setLat(Double lat) {
        this.lat = lat;
    }

    @Column(name = "lng", precision = 22, scale = 0)
    public Double getLng() {
        return this.lng;
    }

    public void setLng(Double lng) {
        this.lng = lng;
    }

    @Column(name = "name", length = 50)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String toJson() {
        return "{\"lat\":" + getLat() + ",\"lng\":" + getLng() + "}";
    }

}
